# Generated by Django 3.2.7 on 2021-10-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emission_parameters',
            old_name='permissible_limit',
            new_name='max_permissible_limit',
        ),
        migrations.RemoveField(
            model_name='emission_parameters',
            name='relation',
        ),
        migrations.AddField(
            model_name='emission_parameters',
            name='min_permissible_limit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
