# Generated by Django 3.2.7 on 2021-10-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20211004_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission_parameters',
            name='min_permissible_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey_metadata',
            name='num_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey_metadata',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey_metadata',
            name='relevant_issues',
            field=models.IntegerField(default=0),
        ),
    ]
