# Generated by Django 3.2.7 on 2021-10-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20211021_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_data',
            name='status',
            field=models.CharField(default='Not addressed', max_length=20),
        ),
    ]
